[package]
name = "app_grpc_api"
version = "0.1.0"
edition = "2021"

[dependencies]
app_core = { path = "../app_core" }
prost = "0.11.0"
tokio = { version = "1", features = ["full"] }
tonic = "0.8.2"

[build-dependencies]
tonic-build = "0.8"